<a href="https://colab.research.google.com/github/FaraazArsath/GUVI---Assignment_11/blob/main/Data_Preprocessing_Assignment11_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [106]:
#Data.csv

**Step 1: Importing the libraries**

In [107]:
import pandas as pd
import numpy as np

**Step 2: Importing dataset**

In [108]:
df = pd.read_csv("Data.csv")
print(df.shape)
df

(10, 4)


Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

**Step 3: Handling the missing data**

In [109]:
# total number of missing value 
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [111]:
df['Age'].describe()

count     9.000000
mean     38.777778
std       7.693793
min      27.000000
25%      35.000000
50%      38.000000
75%      44.000000
max      50.000000
Name: Age, dtype: float64

In [112]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df

Country        Age   Salary Purchased
0   France  44.000000  72000.0        No
1    Spain  27.000000  48000.0       Yes
2  Germany  30.000000  54000.0        No
3    Spain  38.000000  61000.0        No
4  Germany  40.000000      NaN       Yes
5   France  35.000000  58000.0       Yes
6    Spain  38.777778  52000.0        No
7   France  48.000000  79000.0       Yes
8  Germany  50.000000  83000.0        No
9   France  37.000000  67000.0       Yes

In [113]:
df['Salary'].describe()

count        9.000000
mean     63777.777778
std      12265.579662
min      48000.000000
25%      54000.000000
50%      61000.000000
75%      72000.000000
max      83000.000000
Name: Salary, dtype: float64

In [114]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

**Step 4: Encoding categorical data**

In [115]:
df['Purchased'] = df['Purchased'].map({'Yes':1,'No':0})
df

Country        Age        Salary  Purchased
0   France  44.000000  72000.000000          0
1    Spain  27.000000  48000.000000          1
2  Germany  30.000000  54000.000000          0
3    Spain  38.000000  61000.000000          0
4  Germany  40.000000  63777.777778          1
5   France  35.000000  58000.000000          1
6    Spain  38.777778  52000.000000          0
7   France  48.000000  79000.000000          1
8  Germany  50.000000  83000.000000          0
9   France  37.000000  67000.000000          1

**Step 5: Creating a dummy variable**

In [116]:
# creating dummy variable 

df = pd.get_dummies(df,columns=['Country'])
df

Age        Salary  Purchased  Country_France  Country_Germany  \
0  44.000000  72000.000000          0               1                0   
1  27.000000  48000.000000          1               0                0   
2  30.000000  54000.000000          0               0                1   
3  38.000000  61000.000000          0               0                0   
4  40.000000  63777.777778          1               0                1   
5  35.000000  58000.000000          1               1                0   
6  38.777778  52000.000000          0               0                0   
7  48.000000  79000.000000          1               1                0   
8  50.000000  83000.000000          0               0                1   
9  37.000000  67000.000000          1               1                0   

   Country_Spain  
0              0  
1              1  
2              0  
3              1  
4              0  
5              0  
6              1  
7              0  
8              0  
9              0

**Step 6: Splitting the datasets into training sets and Test sets**

In [117]:
X = df.drop(columns='Purchased').values
y = df['Purchased'].values

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=20)

In [118]:
X_train.shape, y_train.shape

((8, 5), (8,))

In [119]:
X_test.shape, y_test.shape

((2, 5), (2,))

**Step 7: Feature Scaling**

In [120]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

array([[ 1.59585612,  1.59407721,  1.29099445, -0.77459667, -0.57735027],
       [-2.1684722 , -1.667133  , -0.77459667, -0.77459667,  1.73205081]])

In [121]:
scaler.transform(X_train)

array([[ 1.95436358,  2.01487853, -0.77459667,  1.29099445, -0.57735027],
       [-0.73444236, -0.6151297 ,  1.29099445, -0.77459667, -0.57735027],
       [ 0.8788412 ,  0.85767491,  1.29099445, -0.77459667, -0.57735027],
       [-1.63071101, -1.03593102, -0.77459667,  1.29099445, -0.57735027],
       [-0.05726161, -1.24633168, -0.77459667, -0.77459667,  1.73205081],
       [-0.3759349 ,  0.33167326,  1.29099445, -0.77459667, -0.57735027],
       [ 0.16182628, -0.00730558, -0.77459667,  1.29099445, -0.57735027],
       [-0.19668118, -0.29952872, -0.77459667, -0.77459667,  1.73205081]])

In [122]:
scaler.transform(X_test)

array([[ 1.59585612,  1.59407721,  1.29099445, -0.77459667, -0.57735027],
       [-2.1684722 , -1.667133  , -0.77459667, -0.77459667,  1.73205081]])